from fpdf import FPDF
import datetime

pdf = FPDF()
pdf.add_page()

# Title
pdf.set_font('Helvetica', 'B', 20)
pdf.cell(0, 15, 'EDA Report - DecodeLabs Internship', ln=True, align='C')
pdf.set_font('Helvetica', '', 11)
pdf.cell(0, 10, 'Project 2 - Exploratory Data Analysis', ln=True, align='C')
pdf.cell(0, 10, f'Date: {datetime.date.today()}', ln=True, align='C')
pdf.ln(5)

# Section 1
pdf.set_font('Helvetica', 'B', 14)
pdf.set_fill_color(30, 30, 100)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 10, '  STEP 1: Basic Statistics', ln=True, fill=True)
pdf.set_text_color(0, 0, 0)
pdf.set_font('Helvetica', '', 10)
pdf.ln(3)
pdf.cell(0, 8, 'Average Order Value (TotalPrice): 1053.97', ln=True)
pdf.cell(0, 8, 'Median Order Value: 823.62', ln=True)
pdf.cell(0, 8, 'Minimum Order: 11.39  |  Maximum Order: 3456.40', ln=True)
pdf.cell(0, 8, 'Insight: Mean > Median = Right Skewed Data. High value orders pulling average up.', ln=True)
pdf.ln(5)

# Section 2
pdf.set_font('Helvetica', 'B', 14)
pdf.set_fill_color(30, 30, 100)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 10, '  STEP 2: Trends', ln=True, fill=True)
pdf.set_text_color(0, 0, 0)
pdf.set_font('Helvetica', '', 10)
pdf.ln(3)
pdf.cell(0, 8, 'Top Product: Printer (181 orders)', ln=True)
pdf.cell(0, 8, 'Lowest Product: Phone (156 orders) - Needs marketing attention!', ln=True)
pdf.cell(0, 8, 'Top Payment Method: Online (258 transactions)', ln=True)
pdf.cell(0, 8, 'Top Referral Source: Instagram (259 customers)', ln=True)
pdf.cell(0, 8, 'RED FLAG: Cancelled(250) + Returned(247) = 497 problematic orders = 41% of all orders!', ln=True)
pdf.cell(0, 8, 'Business Action: Investigate cancellation and return reasons urgently.', ln=True)
pdf.ln(5)

# Section 3
pdf.set_font('Helvetica', 'B', 14)
pdf.set_fill_color(30, 30, 100)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 10, '  STEP 3: Outlier Detection', ln=True, fill=True)
pdf.set_text_color(0, 0, 0)
pdf.set_font('Helvetica', '', 10)
pdf.ln(3)
pdf.cell(0, 8, 'Method Used: IQR (Interquartile Range)', ln=True)
pdf.cell(0, 8, 'Normal Range: 0 to 3330.41', ln=True)
pdf.cell(0, 8, 'Total Outliers Found: 8 orders above 3330.41', ln=True)
pdf.cell(0, 8, 'Highest Outlier: ORD200789 - Tablet - 3456.40', ln=True)
pdf.cell(0, 8, 'Business Action: Flag for investigation - VIP bulk orders or data entry errors?', ln=True)
pdf.ln(5)

# Section 4
pdf.set_font('Helvetica', 'B', 14)
pdf.set_fill_color(30, 30, 100)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 10, '  STEP 4: Correlation Analysis', ln=True, fill=True)
pdf.set_text_color(0, 0, 0)
pdf.set_font('Helvetica', '', 10)
pdf.ln(3)
pdf.cell(0, 8, 'UnitPrice vs TotalPrice: 0.72 (STRONG) - Price drives revenue!', ln=True)
pdf.cell(0, 8, 'Quantity vs TotalPrice: 0.62 (MODERATE) - Bulk orders = Higher bills', ln=True)
pdf.cell(0, 8, 'Quantity vs ItemsInCart: 0.65 - Bulk buyers have more items in cart', ln=True)
pdf.cell(0, 8, 'UnitPrice vs ItemsInCart: 0.00 - Premium buyers buy less but spend more!', ln=True)
pdf.ln(5)

# Summary
pdf.set_font('Helvetica', 'B', 14)
pdf.set_fill_color(30, 30, 100)
pdf.set_text_color(255, 255, 255)
pdf.cell(0, 10, '  FINAL BUSINESS RECOMMENDATIONS', ln=True, fill=True)
pdf.set_text_color(0, 0, 0)
pdf.set_font('Helvetica', '', 10)
pdf.ln(3)
pdf.cell(0, 8, '1. Investigate 41% cancellation/return rate - biggest business risk!', ln=True)
pdf.cell(0, 8, '2. Invest more in Instagram marketing - highest traffic source!', ln=True)
pdf.cell(0, 8, '3. Promote Phone category - lowest sales need a boost!', ln=True)
pdf.cell(0, 8, '4. Focus on UnitPrice optimization - strongest revenue driver!', ln=True)
pdf.cell(0, 8, '5. Investigate 8 outlier orders for fraud or VIP treatment!', ln=True)

pdf.output('EDA_Report.pdf')
print("EDA Report PDF created successfully!")